apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  annotations:
    description.policy.kyverno.io: This Policy ensures that ECS services should have tags assigned to them.
    title.policy.kyverno.io: ECS resource tag
  labels:
    ecs.aws.tags.kyverno.io: ecs-service
  name: validate-ecs-resource-tag
spec:
  rules:
  - name: require-ecs-tag
    match:
      any:
      - type: aws_ecs_service
      - type: aws_ecs_task_definition
    assert:
      all:
      - message: ECS services and tasks are required to have assigned tags. The use of the tag key 'Department' with the tag value 'Accounting' is not permitted.
        check:
          values:
            #(length(keys(tags)) > `0`): true
            #(tags.Department!='Accounting'): true
            (tags != null): true
            (tags.Department!='Accounting'): true
